In [64]:
import numpy as np
from keras.preprocessing.image import ImageDataGenerator

In [65]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense

model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(150, 150, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(5))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [66]:
batch_size = 32
train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

In [67]:
test_datagen = ImageDataGenerator(rescale=1./255)


In [68]:
train_generator = train_datagen.flow_from_directory(
        'F:\\Insofe\\ohers\\Batch_48\\Batch_48\\CNN_Lab_Files\\CNN-Lab\\flow_dir\\data\\train\\train',  # this is the target directory
        target_size=(150, 150),  # all images will be resized to 150x150
        batch_size=batch_size,
        class_mode='categorical')  # since we use binary_crossentropy loss, we need binary labels

# this is a similar generator, for validation data
validation_generator = test_datagen.flow_from_directory(
        'F:\\Insofe\\ohers\\Batch_48\\Batch_48\\CNN_Lab_Files\\CNN-Lab\\flow_dir\\data\\train\\validation',
        target_size=(150, 150),
        batch_size=batch_size,
        class_mode='categorical')

Found 120 images belonging to 5 classes.
Found 45 images belonging to 5 classes.


In [69]:
model.fit_generator(
        train_generator,
        steps_per_epoch=120//batch_size,
        epochs=5,
        validation_data=validation_generator,
        validation_steps=45//batch_size)
model.save_weights('F:\\Insofe\\ohers\\Batch_48\\Batch_48\\CNN_Lab_Files\\CNN-Lab\\flow_dirfirst_try.h5')

Epoch 1/5
3/3 [==============================] - 4s 1s/step - loss: 2.0443 - accuracy: 0.1979 - val_loss: 1.6044 - val_accuracy: 0.2500
Epoch 2/5
3/3 [==============================] - 4s 1s/step - loss: 1.6320 - accuracy: 0.1818 - val_loss: 1.6106 - val_accuracy: 0.1538
Epoch 3/5
3/3 [==============================] - 4s 1s/step - loss: 1.6087 - accuracy: 0.1136 - val_loss: 1.6009 - val_accuracy: 0.2188
Epoch 4/5
3/3 [==============================] - 3s 1s/step - loss: 1.6048 - accuracy: 0.1705 - val_loss: 1.6421 - val_accuracy: 0.0769
Epoch 5/5
3/3 [==============================] - 4s 1s/step - loss: 1.6249 - accuracy: 0.2386 - val_loss: 1.6005 - val_accuracy: 0.2500


In [70]:
model.save("F:\\Insofe\\ohers\\Batch_48\\Batch_48\\CNN_Lab_Files\\CNN-Lab\\model.h5")

In [71]:
print(train_generator.class_indices)

{'c0': 0, 'c1': 1, 'c2': 2, 'c3': 3, 'c4': 4}


In [72]:
test_generator = test_datagen.flow_from_directory(
        'F:\\Insofe\\ohers\\Batch_48\\Batch_48\\CNN_Lab_Files\\CNN-Lab\\flow_dir\\data\\test', 
        target_size=(150, 150), 
        batch_size=batch_size,
        class_mode='categorical')

Found 43 images belonging to 1 classes.


In [73]:
valid_prob = model.predict_generator(validation_generator,steps=2)

In [74]:
valid_prob

array([[0.19282153, 0.1989888 , 0.20866618, 0.20208317, 0.19744034],
       [0.19559018, 0.19881956, 0.20041156, 0.20088032, 0.20429835],
       [0.19896896, 0.20318535, 0.20227626, 0.19427884, 0.20129058],
       [0.19167626, 0.1962752 , 0.19969067, 0.20427753, 0.2080804 ],
       [0.19262001, 0.19799063, 0.20305194, 0.20093015, 0.20540723],
       [0.191215  , 0.19486432, 0.20213795, 0.20949404, 0.2022887 ],
       [0.19561929, 0.20160326, 0.20892608, 0.19763586, 0.19621554],
       [0.19245566, 0.20157588, 0.21206318, 0.19724093, 0.19666427],
       [0.19122456, 0.20014907, 0.21726754, 0.19692011, 0.1944387 ],
       [0.19738111, 0.20492317, 0.20679276, 0.19077829, 0.20012464],
       [0.1915563 , 0.19804098, 0.20982525, 0.20133829, 0.19923918],
       [0.19523893, 0.20038241, 0.20097905, 0.20087855, 0.20252104],
       [0.19525166, 0.2027071 , 0.20792668, 0.19752504, 0.19658951],
       [0.19516002, 0.20089065, 0.20784606, 0.19770305, 0.19840023],
       [0.1969229 , 0.20411387, 0.

In [75]:
test_prob = model.predict_generator(test_generator,steps=2)

In [76]:
test_prob

array([[0.19203582, 0.20026787, 0.21095687, 0.2000326 , 0.19670682],
       [0.19523025, 0.20121314, 0.2076596 , 0.19872406, 0.19717295],
       [0.19554885, 0.20040826, 0.20519584, 0.20088865, 0.19795844],
       [0.19330448, 0.20173658, 0.21175584, 0.19681297, 0.19639005],
       [0.19346805, 0.19758351, 0.20110308, 0.20174205, 0.20610337],
       [0.19496535, 0.19936563, 0.20555174, 0.19857194, 0.20154531],
       [0.19646996, 0.20122862, 0.20322676, 0.19427347, 0.20480119],
       [0.19547302, 0.20356067, 0.20755133, 0.19146536, 0.2019496 ],
       [0.1944359 , 0.2035812 , 0.20859456, 0.19192587, 0.20146245],
       [0.19529949, 0.1990646 , 0.1988647 , 0.20268138, 0.20408984],
       [0.19475071, 0.2005428 , 0.20416044, 0.19765978, 0.20288621],
       [0.1936435 , 0.19848405, 0.20425105, 0.20224427, 0.20137714],
       [0.19401698, 0.19808921, 0.20318328, 0.2019827 , 0.20272778],
       [0.19437027, 0.19956008, 0.20596407, 0.20041475, 0.19969085],
       [0.1946048 , 0.20125088, 0.

In [81]:
test_pred_classes = np.argmax(test_prob, axis=1)

In [82]:
print(test_pred_classes)

[2 2 2 2 4 2 4 2 2 4 2 2 2 2 2 4 4 2 4 2 4 1 2 2 4 2 2 2 2 2 1 4 2 2 2 2 4
 2 2 2 2 2 4]


In [83]:
valid_prob_clases=np.argmax(valid_prob,axis=1)

In [84]:
valid_prob_clases

array([2, 4, 1, 4, 4, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 1, 4,
       4, 4, 1, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 1, 2, 4, 4, 2, 2,
       2], dtype=int64)

In [56]:
print(test_generator.filenames[:5])

['test\\img_100312.jpg', 'test\\img_91724.jpg', 'test\\img_91729.jpg', 'test\\img_91761.jpg', 'test\\img_91769.jpg']
